name: Build project on Push/PR
on: 
  push:  {branches: [main, dev] }
  pull_request:
  workflow_dispatch: {}
jobs:
  build:
    name: Builds for Platform ${{ matrix.targetPlatform }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        unityVersion: 
          - 2020.3.13f1
        targetPlatform:
          - Android # Build android .apk
          - iOS # Build iOS player
    steps:
      # checkout 
      - name: checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          lfs: true

      # # cache library folder from previous build to cut down build time
      # - name: cache library folder
      #   uses: actions/cache@v2
      #   with: 
      #     path: client/TestProject/Library/
      #     key: Library-TestProject-TargetPlatform
      #     restore-keys: |
      #       Library-TestProject-
      #       Library-
      #   if: 

      # build
      - name: Build project
        uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          targetPlatform: ${{ matrix.targetPlatform }}
          projectPath: client/TestProject/
      # upload artifact
      - uses: actions/upload-artifact@v2
        with:
          name: Build-${{ matrix.targetPlatform }}
          path: build/${{ matrix.targetPlatform }}
      
  uploadArtifactToAppCenter:
    name: Upload Build to App Center
    runs-on: ubuntu-latest
    needs: build
    steps:
      # upload APK artifact to AppCenter
      - name: Upload APK to AppCenter
        uses: wzieba/AppCenter-Github-Action@v1.3.2
        with:
          appName: parker@talofagames/Abra-Android
          token: ${{secrets.APP_CENTER_TOKEN}}
          group: orgs/Talofa-Games/apps/R2MH-dev/
          file: build/Android
          notifyTesters: true
          debug: false    
      # upload IPA to AppCenter
      - name: Upload IPA to AppCenter
        uses: wzeiba/AppCenter-GitHub-Action@v1.3.2
        with:
          appName: parker@talofagames/Abra-iOS
          token: ${{ secrets.APP_CENTER_TOKEN }}
          group: orgs/Talofa-Games/apps/R2MH-dev-1/
          file: build/iOS
          notifyTests: true
          debug: false

      # test
      #- name: Run tests
      #  uses: game-ci/unity-test-runner@v2
      #  env:
      #    UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
      #  with:
      #    projectPath: client/TestProject/
      #    githubToken: ${{ secrets.ACCESS_TOKEN_GITHUB }}

      
