name: Build project on Push/PR
on: 
  push:  {branches: [main, dev] }
  pull_request:
  workflow_dispatch: {}
jobs:
  setup:
    name: Performs setup steps
    runs-on: ubuntu-latest
    strategy:
      matrix:
        unityVersion: 
          - 2020.3.13f1
        # targetPlatform:
        #   - Android # Build android .apk
        #   - iOS # Build iOS player
    steps:
      # checkout 
      - name: checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          lfs: true

      # # cache library folder from previous build to cut down build time
      # - name: cache library folder
      #   uses: actions/cache@v2
      #   with: 
      #     path: client/TestProject/Library/
      #     key: Library-TestProject-TargetPlatform
      #     restore-keys: |
      #       Library-TestProject-
      #       Library-
      #   if: 
      
      # test
      #- name: Run tests
      #  uses: game-ci/unity-test-runner@v2
      #  env:
      #    UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
      #  with:
      #    projectPath: client/TestProject/
      #    githubToken: ${{ secrets.ACCESS_TOKEN_GITHUB }}

  buildForAndroid:
    name: Build for Android
    runs-on: ubuntu-latest
    needs: setup # step runs after setup
    strategy: 
      fail-fast: false
      matrix: 
        unityVersion: 
          - 2020.3.13f1
        targetPlatform:
          - Android # Build android .apk
    steps:
      - uses: actions/checkout@v2
        with: 
          lfs: true
      # - uses: actions/cache@v2
      #   with:
      #     path: client/TestProject/Library/
      #     key: Library-${{ matrix.targetPlatform }}
      
      # build
      - name: Build project
        uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          targetPlatform: ${{ matrix.targetPlatform }}
          projectPath: client/TestProject/
      - uses: actions/upload-artifact@v2
        with:
          name: Build-${{ matrix.targetPlatform }}
          path: build/${{ matrix.targetPlatform }}
      #- name: create Android Keystore

  buildForiOS:
    name: Build for iOS
    runs-on: ubuntu-latest
    needs: setup # step runs after setup
    strategy: 
      fail-fast: false
      matrix: 
        unityVersion: 
          - 2020.3.13f1
        targetPlatform:
          - iOS # Build iOS player
    steps:
      - uses: actions/checkout@v2
        with: 
          lfs: true
      # - uses: actions/cache@v2
      #   with:
      #     path: client/TestProject/Library/
      #     key: Library-${{ matrix.targetPlatform }}
      
      # build
      - name: Build project
        uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          targetPlatform: ${{ matrix.targetPlatform }}
          projectPath: client/TestProject/  
      - uses: actions/upload-artifact@v2
        with:
          name: Build-${{ matrix.targetPlatform }}
          path: build/${{ matrix.targetPlatform }}   


      
